"""add_auth_config

Revision ID: 3b8a84212839
Revises: 9e03c93944c3
Create Date: 2026-06-02 10:52:44.037159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b8a84212839'
down_revision: Union[str, Sequence[str], None] = '9e03c93944c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passphrase_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auth_config')
    # ### end Alembic commands ###
