"""initial_schema

Revision ID: 9e03c93944c3
Revises: 
Create Date: 2026-06-02 10:43:44.524099

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9e03c93944c3'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_methods', sa.Column('payment_type', sa.String(length=50), nullable=False))
    op.drop_column('payment_methods', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payment_methods', sa.Column('type', sa.VARCHAR(length=50), nullable=False))
    op.drop_column('payment_methods', 'payment_type')
    # ### end Alembic commands ###
